version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Priyanka100961827
      POSTGRES_DB: labonedb
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: labonedb
      POSTGRES_PASSWORD: Priyanka100961827
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
